# Javascript Node CircleCI 2.0 configuration file
#
# Check {{ '/2.0/language-javascript/' | docs_url }} for more details
#
version: 2

defaults: &defaults
  docker:
    - image: circleci/node:8.9.1

orbs:
  coveralls: coveralls/coveralls@1.0.4

jobs:

  qa:
    docker:
      - image: 'circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install and Test
          command: python3 setup.py install; python3 setup.py test
      - coveralls/upload:
          parallel: true

  npmdeploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: ls -lah ~/; echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: ls -lah; cd partitialajax/src/; npm publish
  pypideploy:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            sudo pip install setuptools wheel twine
          name: Install dependencies
      - run:
          command: |
            ls -lah ~/
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
          name: Init .pypirc
      - run:
          command: |
            python3 setup.py sdist bdist_wheel
          name: Create packages
      - run:
          command: |
            twine upload dist/*
          name: Upload to pypi
workflows:
  version: 2
  publish:
    jobs:
      - npmdeploy
      - pypideploy

